"""add endpoint_url to api_deployments

Revision ID: 73fbd599fe46
Revises: a9d2c6f4b1e7
Create Date: 2026-04-08 22:53:06.376561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73fbd599fe46'
down_revision: Union[str, Sequence[str], None] = 'a9d2c6f4b1e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
